<template>
  <div class="app ft_14" >
      <div class="content pd_10">
          <h4 class=" pd-bottom_10 text-center">以下税率参考文献为《中华人民共和国进境物品完税价格表》</h4>
          <div>
            <table border="1" bordercolor="#e0e0e0" style="border-collapse:collapse;">
                <tbody>
                    <tr class="head">
                        <td>品名及规格</td>
                        <td>单位</td>
                        <td>完税价格<br>（人民币：元）</td>
                        <td>税率</td>
                    </tr>
                    <tr>
                        <td>食品及保健品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>香水</td>
                        <td>瓶</td>
                        <td>300</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td> </td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>唇膏、唇彩</td>
                        <td>支</td>
                        <td>150</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>唇线笔</td>
                        <td>支</td>
                        <td>100</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>其他唇用化妆品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>睫毛膏（液、油）</td>
                        <td>支</td>
                        <td>100</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>眼线笔（液）</td>
                        <td>支</td>
                        <td>100</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>眉笔（眉粉）</td>
                        <td>支</td>
                        <td>100</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>眼影</td>
                        <td>盒</td>
                        <td>100</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>其他眼用化妆品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>粉底及粉底液</td>
                        <td>盒、支</td>
                        <td>200</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>粉饼</td>
                        <td>盒</td>
                        <td>150</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>扑面粉</td>
                        <td>盒</td>
                        <td>150</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>胭脂（粉）、腮红（粉）</td>
                        <td>盒、支</td>
                        <td>100</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>其他粉状化妆品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>特殊功能类化妆品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>洗面奶、洁面霜</td>
                        <td>支、瓶</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>卸妆水</td>
                        <td>支、瓶</td>
                        <td>150</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他清洁用品</td>
                        <td>支、瓶</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>化妆水</td>
                        <td>支、瓶</td>
                        <td>150</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>眼霜</td>
                        <td>支、瓶</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>面霜及乳液</td>
                        <td>支、瓶</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>精华液（素）</td>
                        <td>支、瓶</td>
                        <td>300</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>防晒霜（露、乳液）</td>
                        <td>支</td>
                        <td>150</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>面膜</td>
                        <td>张、瓶</td>
                        <td>20</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>润唇膏</td>
                        <td>支</td>
                        <td>20</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>护手霜</td>
                        <td>支、瓶</td>
                        <td>50</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他护肤用品</td>
                        <td>支、瓶</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>洗/护发液</td>
                        <td>支、瓶</td>
                        <td>30</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他护发用品</td>
                        <td>支、瓶</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他清洁护理品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电吹风机</td>
                        <td>个</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电动剃须刀</td>
                        <td>个</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电动牙刷</td>
                        <td>个</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电动榨汁机</td>
                        <td>台</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>咖啡机</td>
                        <td>台</td>
                        <td>4000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>净水器（含过滤芯）</td>
                        <td>个</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>净水器过滤芯</td>
                        <td>个</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电饭煲</td>
                        <td>个</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>餐具/刀具</td>
                        <td>个、把</td>
                        <td>20</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>餐具/刀具</td>
                        <td>个、把</td>
                        <td>20</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>家用雾化机</td>
                        <td>台</td>
                        <td>2000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>血压计</td>
                        <td>个</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>触屏式手持移动电话机</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>电风扇</td>
                        <td>台</td>
                        <td>400</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电熨斗</td>
                        <td>台</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电暖器</td>
                        <td>台</td>
                        <td>400</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>增/除湿机、增除湿一体机</td>
                        <td>台</td>
                        <td>1500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>空气清新机</td>
                        <td>台</td>
                        <td>1000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>吸尘器</td>
                        <td>台</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>电动剪草机</td>
                        <td>台</td>
                        <td>2000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>灯具</td>
                        <td>台、件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>一体式数字照相机</td>
                        <td>台</td>
                        <td>2000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>可拆卸式数字照相机机身</td>
                        <td>台</td>
                        <td>5000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>可拆卸式数码照相机镜头</td>
                        <td>个</td>
                        <td>2000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>反光式胶片照相机</td>
                        <td>台</td>
                        <td>5000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>一次成像照相机</td>
                        <td>台</td>
                        <td>1000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他照相机</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>录音笔</td>
                        <td>台</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>录音机</td>
                        <td>台</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>收音机</td>
                        <td>台</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>MP3播放器（音频多媒体播放器）</td>
                        <td>台</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>MP4播放器（视频多媒体播放器）</td>
                        <td>台</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他便携式影音设备</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>激光视盘机（LD、VCD、DVD等）</td>
                        <td>台</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>音箱</td>
                        <td>个</td>
                        <td>1000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>便携式收音、录音、激光唱盘一体机</td>
                        <td>台</td>
                        <td>1000</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>CD唱片</td>
                        <td>张</td>
                        <td>50</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>磁盘</td>
                        <td>盘</td>
                        <td>30</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>已录制唱片</td>
                        <td>张</td>
                        <td>50</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>台式个人计算机主机</td>
                        <td>台</td>
                        <td>2000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>主机、显示器一体机</td>
                        <td>台</td>
                        <td>3000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>键盘式笔记本电脑</td>
                        <td>台</td>
                        <td>2000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>触屏式笔记本电脑</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>主板</td>
                        <td>块</td>
                        <td>500</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>中央处理器(CPU)</td>
                        <td>个</td>
                        <td>500</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>4G及以下</td>
                        <td>条</td>
                        <td>200</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>4G以上</td>
                        <td>条</td>
                        <td>300</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>功能卡</td>
                        <td>块</td>
                        <td>300</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>鼠标</td>
                        <td>个</td>
                        <td>50</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>键盘</td>
                        <td>个</td>
                        <td>80</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>音箱</td>
                        <td>个</td>
                        <td>50</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>19英寸及以下</td>
                        <td>台</td>
                        <td>800</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>19英寸以上，24英寸及以下</td>
                        <td>台</td>
                        <td>1200</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>24英寸以上</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>17英寸及以下</td>
                        <td>台</td>
                        <td>300</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>17英寸以上</td>
                        <td>台</td>
                        <td>500</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>其他显示器</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>CD</td>
                        <td>台</td>
                        <td>100</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>DVD</td>
                        <td>台</td>
                        <td>200</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>其他驱动器</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>1T及以下</td>
                        <td>个</td>
                        <td>300</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>1T以上2T以下（含2T）</td>
                        <td>个</td>
                        <td>500</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>2T以上</td>
                        <td>个</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>U盘</td>
                        <td>个</td>
                        <td>50</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>其他存储器</td>
                        <td>个、盒</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>电子(纸)书</td>
                        <td>台</td>
                        <td>800</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>笔</td>
                        <td>支</td>
                        <td>50</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他文具用品</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>便携式游戏机</td>
                        <td>台</td>
                        <td>1000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>电脑游戏机</td>
                        <td>台</td>
                        <td>2000</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>其他游戏机</td>
                        <td>台</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>游戏碟、盘、卡</td>
                        <td>张、个</td>
                        <td>60</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>游戏机遥控器、控制器</td>
                        <td>个</td>
                        <td>200</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>其他游戏机配件、附件</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>纸牌游戏用品</td>
                        <td>套</td>
                        <td>50</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>棋类产品</td>
                        <td>套</td>
                        <td>50</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>其他桌上或室内游戏用品</td>
                        <td>件、套</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>外衣</td>
                        <td>件</td>
                        <td>300</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>外裤</td>
                        <td>条</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>内衣裤</td>
                        <td>条/件</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>衬衫/T恤衫</td>
                        <td>件</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他衣着</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>帽子</td>
                        <td>件</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>丝巾、头巾、围巾</td>
                        <td>条</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>领带</td>
                        <td>条</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>腰带</td>
                        <td>条</td>
                        <td>100</td>
                        <td>0.3</td>
                    </tr>
                    <tr>
                        <td>手套</td>
                        <td>双</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他配饰</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>毛毯、被子、床罩、睡袋</td>
                        <td>床、件</td>
                        <td>400</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>枕头、床单、毛巾被、被套</td>
                        <td>条、件</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>箱</td>
                        <td>个</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>挎包、背包、提包</td>
                        <td>个</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>钱包、钥匙包</td>
                        <td>个</td>
                        <td>100</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他箱包</td>
                        <td>个</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>皮鞋</td>
                        <td>双</td>
                        <td>300</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>皮靴</td>
                        <td>双</td>
                        <td>400</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>运动鞋</td>
                        <td>双</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他鞋靴</td>
                        <td>双</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>高档手表（审定价格在人民币10000元及以上）</td>
                        <td>块</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                    <tr>
                        <td>石英表（电子表）</td>
                        <td>块</td>
                        <td>200</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>机械表</td>
                        <td>块</td>
                        <td>500</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>其他表</td>
                        <td>块</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>－金银</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>15%</td>
                    </tr>
                    <tr>
                        <td>钻石及钻石首饰</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>30%</td>
                    </tr>
                    <tr>
                        <td>贵重首饰及珠宝玉石</td>
                        <td>件</td>
                        <td>按照申报价值或市场价值</td>
                        <td>60%</td>
                    </tr>
                </tbody>
            </table>
          </div>
          <div class=" pd-top_20">
              <p class="info_sub pd-bottom_10">关税的计算方式为「完税价格 × 税率」；价格超过完税价格范围或没有完税价格的商品，关税的计算方式为「商品价格 × 关税」；实际关税以海关出具的税单为准。可详询客服。</p>
              <p class="info">对于以上信息有任何疑问，请在工作时间联系客服或留言。</p>
          </div>    
      </div>
  </div>
</template>

<script>
export default {
  head: {
    title: '关税说明'
  }
}
</script>

<style lang="scss" scoped>
table{
  width: 100%;
  .head{
    background: #eee;
  }
  td{
    padding: 5px 8px;
  }
}
p{
 text-align:justify;
}
</style>


